name: stunning_extensions
description: > 
  A lightweight Dart package providing stunning extension methods for Strings, Dates, Numbers, and more, designed to make your code cleaner, shorter, and more readable.
version: 1.0.0
repository: https://github.com/houssemeddinefadhli81/stunning-extensions
homepage: https://github.com/houssemeddinefadhli81/stunning-extensions

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.0

topics:
  - dart
  - flutter
  - extensions
  - dart-extensions
  - flutter-extensions